name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements-dev.lock
      - name: Install dependencies
        run: pip install -r requirements-dev.lock --no-deps
      - name: Run pytest
        run: pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements-dev.lock
      - name: Install dependencies
        run: pip install -r requirements-dev.lock --no-deps
      - name: Run mypy
        run: mypy .
      - name: Run black
        run: black . --check
      - name: Run ruff
        run: ruff check .
