name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Poppler
        run: |
          if [[ ${{ runner.os }} == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install poppler-utils
          elif [[ ${{ runner.os }} == "macOS" ]]; then
            brew update
            brew install poppler
          fi
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run pytest
        run: poetry run pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run mypy
        run: poetry run mypy .
      - name: Run black
        run: poetry run black . --check
      - name: Run ruff
        run: poetry run ruff .
