name: Python package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv pip install build twine
      - run: python -m build
      - run: python -m twine upload --non-interactive -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
