name: Python package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: eifinger/setup-rye@v1
      - run: rye build
      - run: rye publish --token ${{ secrets.PYPI_TOKEN }} --yes
